spring:
  jpa:
    database: mysql
    show-sql: true
    hibernate:
      ddl-auto: update
  datasource:
    druid:
      url: jdbc:mysql://localhost:3306/db_partner_manager?useSSL=false&serverTimezone=UTC
      username: root
      password: aa123456.

  redis:
    host: localhost
    port: 6379